In [1]:
# Environment preparation
import sys
!pip install expectexception

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
# Preparing environment
import expectexception

# %%expect_exception TypeError

# 1. NUMPY BASICS

In [3]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np

# Let's define a one-dimensional array 
my_list = [10, 20, 50, 60, 70]
my_list, type(my_list)

([10, 20, 50, 60, 70], list)

In [4]:
# Let's create a numpy array from the list "my_list"
x = np.array(my_list)
x, type(x)

(array([10, 20, 50, 60, 70]), numpy.ndarray)

In [5]:
# Multi-dimensional (Matrix definition) 
matrix = np.array([[5, 8], [9, 13]])
matrix

array([[ 5,  8],
       [ 9, 13]])

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [6]:
my_array = np.array([[4, 6, 8, 7],
                     [20, 5, 6, 9]])
my_array

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [7]:
# "rand()" uniform distribution between 0 and 1
print(np.random.rand())
print(np.random.rand(10))

0.03602692640002836
[0.15968156 0.39322461 0.11087337 0.85242376 0.4589982  0.42762698
 0.70018774 0.82230443 0.92608993 0.24130359]


In [8]:
# you can create a matrix of random number as well
np.random.rand(2,2)

array([[0.5198077 , 0.90486891],
       [0.72486159, 0.00863099]])

In [9]:
# "randn()" normal distribution between -1 and 1
np.random.randn(15)

array([ 0.4685472 , -1.84430294,  0.49440935, -0.76527393,  0.06867863,
       -0.22920168, -0.46728197,  0.61890347, -0.75663359, -0.16378434,
        1.29809037,  0.94960244, -0.25738813,  1.32726221, -1.18380492])

In [10]:
# "randint" is used to generate random integers between upper and lower bounds
print(np.random.randint(10, 50))

# "randint" can be used to generate a certain number of random itegers as follows
np.random.randint(10, 50, 6)

43


array([15, 38, 18, 46, 11, 38])

In [11]:
# np.arange creates an evenly spaced values within a given interval
print(np.arange(start=-10, stop=10, step=5))
print(np.arange(-10, 10, 5))
print(np.arange(0, 51, 10))
print(np.arange(10))

[-10  -5   0   5]
[-10  -5   0   5]
[ 0 10 20 30 40 50]
[0 1 2 3 4 5 6 7 8 9]


In [12]:
# Create an evenly spaced values over a specified interval.
np.linspace(-10, 10, 6)

array([-10.,  -6.,  -2.,   2.,   6.,  10.])

In [13]:
# create a diagonal of ones and zeros everywhere else
print(np.eye(5), '\n')
print(np.eye(5, k=2))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
# Array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
# Matrices of ones
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# Array of zeros
print(np.zeros(10))
print(np.zeros((2, 4)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [17]:
while True:
  try:
    x = int(input('Enter a positive integer (0 to exit): '))
    if x < 0:
      raise Exception('Sorry, only positive numbers are allowed!')
    elif x == 0:
      break
    
    print(f'Formatted random array:')
    print(np.random.randint(0, x, 20))
  
  except Exception as e:
    print(f'{e}\nTry again!...')

Enter a positive integer (0 to exit): hello
invalid literal for int() with base 10: 'hello'
Try again!...
Enter a positive integer (0 to exit): -10
Sorry, only positive numbers are allowed!
Try again!...
Enter a positive integer (0 to exit): 10
Formatted random array:
[5 5 6 2 8 4 7 9 4 4 5 9 5 7 8 8 8 3 9 1]
Enter a positive integer (0 to exit): 0


# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [18]:
# Let's define a one-dimensional array 
x = np.array([-30, 4, 50, 60, 29, 15, 22, 90])
x

array([-30,   4,  50,  60,  29,  15,  22,  90])

In [19]:
# Get Length of a numpy array
len(x)

8

In [20]:
# Get shape
x.shape

(8,)

In [21]:
# Obtain the datatype
x.dtype, type(x)

(dtype('int64'), numpy.ndarray)

In [22]:
# Reshape 1D array into a matrix
print(x)
x.reshape((2,4))

[-30   4  50  60  29  15  22  90]


array([[-30,   4,  50,  60],
       [ 29,  15,  22,  90]])

In [23]:
# Obtain the maximum element (value)
x.max()

90

In [24]:
# Obtain the minimum element (value)
x.min()

-30

In [25]:
# Obtain the location of the max element
print('Array             :', x)
print('Max value         :', x.max())
print('Index of max value:', x.argmax())

Array             : [-30   4  50  60  29  15  22  90]
Max value         : 90
Index of max value: 7


In [26]:
# Obtain the location of the min element
print('Array             :', x)
print('Min value         :', x.min())
print('Index of min value:', x.argmin())

Array             : [-30   4  50  60  29  15  22  90]
Min value         : -30
Index of min value: 0


**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

In [27]:
print(np.arange(300, 500, 10).reshape((4, 5)))

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [28]:
a = np.random.randint(-1000, 1000, (20, 20))
print('Array:')
print(a, '\n')
print('Max value:', a.max())
print('Min value:', a.min())
print('Average  :', a.mean())

Array:
[[ 590  252 -647  845 -912  503 -480  430  813 -174 -366 -134 -318 -829
  -738  682  391 -438  448 -116]
 [ 922  830  -73  860  754  960  331 -670 -716 -203 -103 -708 -680  765
   737 -361  251 -943 -626 -144]
 [ 336 -361 -588 -733   54 -600 -218 -954 -494  686 -227 -237 -580 -542
  -669 -136 -765 -651  856 -543]
 [-664  -49 -629 -889  213 -425  913 -300  797 -879  207 -799  338  -65
   714  462 -124  896  -80  150]
 [ 275   33  664 -796 -126 -887  483  158 -299  759 -127 -776   93  123
   604 -157  370 -284   98  282]
 [ 453  511  813  978 -912 -857  180  -96   76  996  950 -465  -99  312
   659  954  863  752  -67    1]
 [-271 -821  100  421   21 -497  711 -282 -231  151  -74  914 -832 -392
  -835  506  606  483  654 -476]
 [ -31  234 -267   70  514 -211  164  978  228  -16  759 -619  779  963
  -850 -875 -212  545 -332  539]
 [-252  740 -273 -982 -544 -612  995 -909 -874  698 -397  685  377 -686
    75  379  195   49  632   96]
 [ -76 -826 -651  768 -436   69   80  -97 -779 -

# 4. MATHEMATICAL OPERATIONS

In [29]:
# np.arange() returns an evenly spaced values within a given interval
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# Add 2 numpy arrays together
x = np.arange(1, 10)
y = np.arange(1, 10)

x + y

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
# sqrt
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [32]:
# power 2
print(x**2)
np.square(x)

[ 1  4  9 16 25 36 49 64 81]


array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [33]:
# e^x
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

In [34]:
x = np.array([3, 20, 30])
y = np.array([4, 6, 7])

print(np.sqrt((x-y)**2))
print(np.abs(x-y))

[ 1. 14. 23.]
[ 1 14 23]


# 5. SLICING AND INDEXING 

In [35]:
x = np.array([20, 40, 50, 21, 15])
x

array([20, 40, 50, 21, 15])

In [36]:
# Access specific index from the numpy array
x[0]

20

In [37]:
# Starting from the first index 0 up until and NOT inlcluding the last element
x[0:3]

array([20, 40, 50])

In [38]:
# Broadcasting, altering several values in a numpy array at once
print(x)
x[0:2] = 10
print(x)

[20 40 50 21 15]
[10 10 50 21 15]


In [39]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[2, 9, 3, 7, 5],
       [6, 5, 6, 4, 3],
       [8, 2, 9, 1, 3],
       [2, 6, 8, 8, 8],
       [2, 4, 2, 8, 6]])

In [40]:
# Get a row from a mtrix
matrix[2]

array([8, 2, 9, 1, 3])

In [41]:
# Get one element
matrix[2,0]

8

In [42]:
# Getting an small portion of the matrix
print('Full matrix: ')
print(matrix, '\n\n')
print('Small portion of the matrix:')
print(matrix[:3], '\n')
print(matrix[2:], '\n')
print(matrix[:, :2], '\n')
print(matrix[:, 2:])

Full matrix: 
[[2 9 3 7 5]
 [6 5 6 4 3]
 [8 2 9 1 3]
 [2 6 8 8 8]
 [2 4 2 8 6]] 


Small portion of the matrix:
[[2 9 3 7 5]
 [6 5 6 4 3]
 [8 2 9 1 3]] 

[[8 2 9 1 3]
 [2 6 8 8 8]
 [2 4 2 8 6]] 

[[2 9]
 [6 5]
 [8 2]
 [2 6]
 [2 4]] 

[[3 7 5]
 [6 4 3]
 [9 1 3]
 [8 8 8]
 [2 8 6]]


**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [43]:
x = np.array(
  [[ 2,  30, 20, -2, -4],
   [ 3,  4,  40, -3, -2],
   [-3,  4, -6, 90, 10],
   [25, 45, 34, 22, 12],
   [13, 24, 22, 32, 37]]  
)
print('Original matrix: ')
print(x, '\n\n')

# Replace the last row with -1
# x[-1, :] = -1 # Also this way
x[-1] = -1

# Multiply the 2x2 matrix in the upper right corner by 2
x[:2,:2] = x[:2,:2]**2

print('After modifications: ')
print(x)

Original matrix: 
[[ 2 30 20 -2 -4]
 [ 3  4 40 -3 -2]
 [-3  4 -6 90 10]
 [25 45 34 22 12]
 [13 24 22 32 37]] 


After modifications: 
[[  4 900  20  -2  -4]
 [  9  16  40  -3  -2]
 [ -3   4  -6  90  10]
 [ 25  45  34  22  12]
 [ -1  -1  -1  -1  -1]]


# 6. ELEMENTS SELECTION (CONDITIONAL)

In [44]:
# Let's create a new matrix
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[3, 5, 6, 8, 3],
       [8, 6, 5, 6, 7],
       [2, 5, 2, 5, 2],
       [7, 7, 8, 7, 4],
       [5, 8, 3, 3, 9]])

In [45]:
# Select only items > 3
filter = matrix>3

print(filter)
matrix[filter]

[[False  True  True  True False]
 [ True  True  True  True  True]
 [False  True False  True False]
 [ True  True  True  True  True]
 [ True  True False False  True]]


array([5, 6, 8, 8, 6, 5, 6, 7, 5, 5, 7, 7, 8, 7, 4, 5, 8, 9])

In [46]:
# Select only even numbers
filter = matrix%2==0

print(filter)
matrix[filter]

[[False False  True  True False]
 [ True  True False  True False]
 [ True False  True False  True]
 [False False  True False  True]
 [False  True False False False]]


array([6, 8, 8, 6, 6, 2, 2, 2, 8, 4, 8])

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [47]:
x = np.array([
  [ 2, 30, 20, -2, -4],
  [ 3,  4, 40, -3, -2],
  [-3,  4, -6, 90, 10],
  [25, 45, 34, 22, 12],
  [13, 24, 22, 32, 37]
])
print('Original matrix: ')
print(x, '\n\n')

# Replace negative elements by 0
filter = x < 0
x[filter] = 0

# Replace odd elements with 25
filter = x%2 == 0
x[~filter] = 25

print('After modifications: ')
print(x)

Original matrix: 
[[ 2 30 20 -2 -4]
 [ 3  4 40 -3 -2]
 [-3  4 -6 90 10]
 [25 45 34 22 12]
 [13 24 22 32 37]] 


After modifications: 
[[ 2 30 20  0  0]
 [25  4 40  0  0]
 [ 0  4  0 90 10]
 [25 25 34 22 12]
 [25 24 22 32 25]]


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [48]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

array([[[ 4,  6,  8,  7],
        [20,  5,  6,  9]]])

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [49]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

Please enter a positive integer value: 10


array([6, 8, 7, 3, 5, 1, 3, 1, 2, 3, 2, 6, 3, 6, 7, 3, 1, 2, 5, 1])

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [50]:
x = np.arange(300, 500, 10)
x.shape

(20,)

In [51]:
x = x.reshape(4, 5)
print(x)

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [52]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

[[  124    57  -840   338   518  -903  -486  -580   892   592  -438  -862
   -933  -245   318   780   -95   422  -832   573]
 [ -953   -65  -718  -646  -155   871   374   675  -133    33   930  -830
    855  -448  -871  -695  -350   804   564   827]
 [   30    96   496   748   646  -544   545   574   686   948  -357   987
    535   578   614  -236    78 -1000  -209  -636]
 [  401  -507  -338  -446  -722   697  -959  -828  -498    42   169  -618
   -984   649   578  -381   316   515   245   589]
 [ -530   992  -380  -584   797   740    85  -943  -964   949  -142   -40
    239   895  -110  -692  -788  -762  -789  -501]
 [ -780   410  -823  -922    90  -561  -835  -492  -581   560   512   803
    519   408   -83  -379  -535  -587   393   961]
 [ -232  -611    62   201  -907   947  -603  -813   863   162   491   536
    360   277   134  -405  -920  -878  -188   446]
 [   12   397  -329  -688  -892  -720  -497   587  -331  -656  -723   111
    559  -752  -476   767  -204  -437     7   758]


**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [53]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

array([ 5.        , 20.88061302, 30.8058436 ])

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [54]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [55]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

In [56]:
X[:2, 3:] = X[:2, 3:] * 2

In [57]:
X

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [58]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40, 25,  0],
       [25,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])